config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root "items#index"

  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      post 'step2'
      get 'step3'
      post 'step3'
      get 'step4'
      get "/jip" => "signup#jip"
      post 'create_step4' => "signup#create_step4"
      get 'step5'
      get 'set'
      get 'done'
    end
  end

  resources :items do
    resources :good, only: [:create, :destroy]
    get "buy" => "items#buy"
    collection do
      get 'category_children', defaults: { format: 'json' }
      get "category_grandchildren", defaults: { format: "json"}
      get "search"
      get "search_more"
    end
  end

  resources :items ,only: [:edit] do
    member do
      get 'category_children', defaults: { format: 'json' }
      get "category_grandchildren", defaults: { format: "json"}
    end
    patch "edit_update" => "items#edit_update"
  end

  get "more/:id" => "items#more"
  get "buy_after" => "items#buy_after"

  resources :users do
    get "edit_item/:id" => "users#edit_item"
    get "logout" => "users#logout"
    get "profile" => "users#profile"
    get "exhibiting" => "users#exhibiting"
    get "identification" => "users#identification"
    get "trade/:id" => "users#trade"
    get "trade_after" => "users#trade_after"
    get "sold/:id" => "users#sold"
  end

  resources :credit_cards do
    collection do
      post 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end

  resources :purchase, only: [:index] do
    collection do
      get 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end

end

app/models/credit_card.rb
class CreditCard < ApplicationRecord
  belongs_to :user
  validates :customer_id,presence: true
  validates :card_id,presence: true
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController

  require "payjp"
  before_action :set_card

  def new
    card = CreditCard.where(user_id: current_user.id).first

    if card.present?
      redirect_to root_path
    end

  end

  def pay #payjpとCredit_cardsテーブルのレコード作成
    Payjp.api_key = 'sk_test_f98999ddca480c61d3498ee7'  # ここでテスト鍵をセットしてあげる(環境変数にしても良い)

    if params['payjp-token'].blank?  # paramsの中にjsで作った'payjpTokenが存在するかどうか
      redirect_to action: "new"
    else
      customer = Payjp::Customer.create(
    # description: '登録テスト', #なくてもOK
    # email: current_user.email, #なくてもOK
    card: params['payjp-token'],
    metadata: {user_id: current_user.id} #なくてもOK
    )

    @card = CreditCard.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)

      if @card.save
        if request.referer&.include?("/signup/step5")
          redirect_to set_signup_index_path
        else
          redirect_to action: "show"
        end
      else
        redirect_to action: "pay"
      end

    end

  end


  def delete  #PayjpとCardデータベースを削除します
    card = CreditCard.where(user_id: current_user.id).first
    if card.blank?
      redirect_to root_path
    else
      Payjp.api_key = 'sk_test_f98999ddca480c61d3498ee7'
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
  end

  def show  #Cardのデータpayjpに送り情報を取り出します
    card = CreditCard.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = 'sk_test_f98999ddca480c61d3498ee7'
      customer = Payjp::Customer.retrieve(card.customer_id)
      @default_card_information = customer.cards.retrieve(card.card_id)
    end
  end

  private

  def set_card
    @card = CreditCard.where(user_id: current_user.id)
  end

end

app/views/credit_cards/new.html.haml
.registration__header

.registration__first
  .registration__first__box
    = form_tag(pay_credit_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
      %h2.registration__first__box__top 支払い方法
      .registration__first__box__middle
        .registration__first__box__middle__input
          .registration__first__box__middle__input__name
            %label カード番号
            %span 必須
            = text_field_tag "number", "", class: "number", placeholder: "半角数字のみ" ,maxlength: "16", type: "text", id: "card_number"
            = image_tag "card_list.png", class: "card_list"
        .registration__first__box__middle__input
          .registration__first__box__middle__input__name
            = label_tag "有効期限"
            %span 必須
          .registration__first__box__middle__input__double__card
            %select#exp_month{name: "exp_month", type: "text"}
              %option{value: ""} --
              %option{value: "1"}01
              %option{value: "2"}02
              %option{value: "3"}03
              %option{value: "4"}04
              %option{value: "5"}05
              %option{value: "6"}06
              %option{value: "7"}07
              %option{value: "8"}08
              %option{value: "9"}09
              %option{value: "10"}10
              %option{value: "11"}11
              %option{value: "12"}12
            %span 月/

            %select#exp_year{name: "exp_year", type: "text"}
              %option{value: ""} --
              %option{value: "2019"}19
              %option{value: "2020"}20
              %option{value: "2021"}21
              %option{value: "2022"}22
              %option{value: "2023"}23
              %option{value: "2024"}24
              %option{value: "2025"}25
              %option{value: "2026"}26
              %option{value: "2027"}27
              %option{value: "2028"}28
              %option{value: "2029"}29
            %span 年

        .registration__first__box__middle__input
          .registration__first__box__middle__input__name
            %label セキュリティコード
            %span 必須
          = text_field_tag "cvc", "", class: "cvc", placeholder: "カード背面3~4桁の番号", maxlength: "4", id: "cvc"
          %a{href: "#"} カード裏面の番号とは？
        .registration__first__box__middle__input
          #card_token
            = submit_tag "追加する", class: "last_submit", id: "token_submit"

  = render partial: "devise/layout/footer"

app/views/credit_cards/show.html.haml
.sign_in__page
  .registration__header__logo
    =link_to root_path do
      =image_tag "header_logo.png", class: "logo"
.registration__first
  .registration__first__box
    = form_tag(pay_credit_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
      %h2.registration__first__box__top クレジットカード情報

      .registration__first__box__middle
        .registration__first__box__middle__input
          .registration__first__box__middle__input__name
            %h3 カード番号
            .pay_number
              = "**** **** **** " + @default_card_information.last4

        .registration__first__box__middle__input
          .registration__first__box__middle__input__name
            %h3 有効期限
            .pay_number
              - exp_month = @default_card_information.exp_month.to_s
              - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
              = exp_month + " / " + exp_year

        .registration__first__box__middle__input
          .registration__first__box__middle__input__name
            .pay_buttons
              = form_tag(delete_credit_cards_path, method: :post, id: 'charge-form',  name: "inputForm") do
                %input{ type: "hidden", name: "card_id", value: "" }
                %button.pay_button 削除する
              = link_to user_path do
                %button.pay_button マイページに戻る

  = render partial: "devise/layout/footer"