config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root "items#index"

  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      post 'step2'
      get 'step3'
      post 'step3'
      get 'step4'
      get "/jip" => "signup#jip"
      post 'create_step4' => "signup#create_step4"
      get 'step5'
      get 'set'
      get 'done'
    end
  end

  resources :items do
    resources :good, only: [:create, :destroy]
    get "buy" => "items#buy"
    collection do
      get 'category_children', defaults: { format: 'json' }
      get "category_grandchildren", defaults: { format: "json"}
      get "search"
      get "search_more"
    end
  end

  resources :items ,only: [:edit] do
    member do
      get 'category_children', defaults: { format: 'json' }
      get "category_grandchildren", defaults: { format: "json"}
    end
    patch "edit_update" => "items#edit_update"
  end

  get "more/:id" => "items#more"
  get "buy_after" => "items#buy_after"

  resources :users do
    get "edit_item/:id" => "users#edit_item"
    get "logout" => "users#logout"
    get "profile" => "users#profile"
    get "exhibiting" => "users#exhibiting"
    get "identification" => "users#identification"
    get "trade/:id" => "users#trade"
    get "trade_after" => "users#trade_after"
    get "sold/:id" => "users#sold"
  end

  resources :credit_cards do
    collection do
      post 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end

  resources :purchase, only: [:index] do
    collection do
      get 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable,
          :omniauthable,
          omniauth_providers: %i[facebook google_oauth2]

  has_many :sns_credentials, dependent: :destroy
  has_one :credit_card
  has_one :delivery

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  def self.find_oauth(auth) # omniauthのコールバック時に呼ばれるメソッド
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.find_by(uid: uid, provider: provider)

    if snscredential.present? #sns登録のみ完了してるユーザー
      user = User.find_by(id: snscredential.user_id)
      unless user.present? #ユーザーが存在しないなら
        password = Devise.friendly_token[0, 8]#パスワード生成
        user = User.new(
          # snsの情報を取ってくる
          name: auth.info.name,
          email: auth.info.email,
          password: password,
          password_confirmation: password
          )

        end
    sns = snscredential

    else #sns登録 未 の場合
      user = User.find_by(email: auth.info.email)
      if user.present? #会員登録 済 の場合
        sns = SnsCredential.new(
          uid: uid,
          provider: provider,
          user_id: user.id
          )
        else #会員登録 未 の場合
          password = Devise.friendly_token[0, 8]#パスワードを生成(hidden_fieldに入力)
        user = User.new(
          name: auth.info.name,
          email: auth.info.email,
          password: password,
          password_confirmation: password
        )
        sns = SnsCredential.create(
          uid: uid,
          provider: provider
        )
      end
    end
    # hashでsnsのidを返り値として保持しておく
    return { user: user , sns_id: sns.id }
  end

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name,presence: true, length: {maximum: 20}
  validates :email,presence: true, uniqueness: true, format: { with: VALID_EMAIL_REGEX }
  validates :password,presence: true
  validates :last_name,presence: true
  validates :first_name,presence: true
  validates :last_name_kana,presence: true
  validates :first_name_kana,presence: true
  validates :birthday, presence: true
  validates :tel_number, presence: true

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_for(:facebook) #コールバック
  end

  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    info = User.find_oauth(request.env["omniauth.auth"]) #usersモデルのメソッド
    @user = info[:user]
    sns_id = info[:sns_id]
    # binding.pry
    if @user.persisted? #userが存在したら
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?

    # elsif reqest.env["omnioauth.origin"].inclueds?("sign_up")
    #   sessionのomnioAuthのデータ入れてるところに環境変数を入れて、exceptなんちゃら
    # render template:



    else #userが存在しなかったら

      # session["devise.sns_id"] = sns_id #sns_credentialのid devise.他のアクションに持ち越せる(少し難)
      session["devise.sns_id"] = info #sns_credentialのデータをsessionに格納し他のアクションに持ち越す
# binding.pry
      # @user = User.new
      render template: "/signup/step1" #redirect_to だと更新してしまうのでrenderで
    end
  end

  def failure
    redirect_to root_path and return
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  # def create
  #   # binding.pry
  #   if  params[:user][:password] == "" #sns登録なら
  #       params[:user][:password] = "Devise.friendly_token.first(6)" #deviseのパスワード自動生成機能を使用
  #       params[:user][:password_confirmation] = "Devise.friendly_token.first(6)"
  #   super
  #   # binding.pry
  #     sns = SnsCredential.update(user_id: @user.id)
  #   else #email登録なら
  #     # binding.pry
  #     super
  #   end
  # end


end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :pull
  before_action :set_user

  def update
    if @user.id == current_user.id
      @user.update(profile: params[:user][:profile])
      redirect_to "/users/#{current_user.id}"
    end
  end

  def exhibiting
    @user = User.find(current_user.id)
    tradings = Trading.where(saler_id: current_user.id, sale_state: "exhibit")
    trading = tradings.map {|t| t[:item_id]}
    @items = Item.where(id: trading)

    trade = Trading.where(saler_id: current_user.id, sale_state: "trade")
    trading_now = trade.map {|t| t[:item_id]}
    @trading_items = Item.where(id: trading_now)

    sale = Trading.where(saler_id: current_user.id, sale_state: "sold")
    sold = sale.map {|t| t[:item_id]}
    @sold_items = Item.where(id: sold)

    @exhibit_images = Image.where(item_id: @items.map{|a| a.id})
    @trade_images = Image.where(item_id: @trading_items.map{|a|a.id})
    @sold_images = Image.where(item_id: @sold_items.map{|a|a.id})
  end

  def edit_item
    @item = Item.find(params[:id])
    @category_gc= Category.find(@item[:category_index])
    @category_c = @category_gc.parent
    @category = @category_c.parent
    @image = Image.find_by(item_id: @item.id).url
  end

  def trade
    @item = Item.find(params[:id])
    @category_gc= Category.find(@item[:category_index])
    @category_c = @category_gc.parent
    @category = @category_c.parent
    @trading = Trading.find_by(item_id: params[:id])
    @user = User.find(@trading.saler_id)
    @image = Image.find_by(item_id: @item.id).url
  end

  def trade_after
    @user = User.find(current_user.id)
  end

  def sold
    @user = User.find(current_user.id)
    @item = Item.find(params[:id])
  end

  def pull
    @parents = Category.where(ancestry: nil)
  end

  def set_user
    @user = User.find(current_user.id)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_side_bar.html.haml
.side_bar
  .side_bar__main
    %ul
      %li
        = link_to 'マイページ', "/users/#{@user.id}"
        %i.fa.fa-chevron-right
      %li
        = link_to 'お知らせ', " "
        %i.fa.fa-chevron-right
      %li
        =link_to 'やることリスト'," "
        %i.fa.fa-chevron-right
      %li
        =link_to 'いいね！一覧', " "
        %i.fa.fa-chevron-right
      %li
        =link_to '出品する', " "
        %i.fa.fa-chevron-right
      %li
        =link_to '出品した商品 - 出品中',"/users/#{@user.id}/exhibiting"
        %i.fa.fa-chevron-right
      %li
        =link_to '出品した商品 - 取引中', " "
        %i.fa.fa-chevron-right
      %li
        =link_to'出品した商品 - 売却済み', " "
        %i.fa.fa-chevron-right
      %li
        =link_to'購入した商品 - 取引中'," "
        %i.fa.fa-chevron-right
      %li
        =link_to'購入した商品 - 過去の取引'," "
        %i.fa.fa-chevron-right
      %li
        =link_to'ニュース一覧'," "
        %i.fa.fa-chevron-right
      %li
        =link_to'評価一覧'," "
        %i.fa.fa-chevron-right
      %li
        =link_to'ガイド'," "
        %i.fa.fa-chevron-right
      %li
        =link_to'お問い合わせ'," "
        %i.fa.fa-chevron-right

  %p メルペイ
  .side_bar__middle
    %ul
      %li
        =link_to'売上・振込申請'," "
        %i.fa.fa-chevron-right
      %li
        =link_to'ポイント'," "
        %i.fa.fa-chevron-right
  %p 設定
  .side_bar__bottom
    %ul
      %li
        =link_to'プロフィール',"/users/#{@user.id}/profile"
        %i.fa.fa-chevron-right
      %li
        =link_to'発送元・お届け先住所変更'," "
        %i.fa.fa-chevron-right
      %li
        =link_to'支払い方法',"/credit_cards/show"
        %i.fa.fa-chevron-right
      %li
        =link_to'メール/パスワード'," "
        %i.fa.fa-chevron-right
      %li
        =link_to'本人情報',"/users/#{@user.id}/identification"
        %i.fa.fa-chevron-right
      %li
        =link_to'電話番号の確認'," "
        %i.fa.fa-chevron-right
      %li
        =link_to'ログアウト',"/users/#{@user.id}/logout"
        %i.fa.fa-chevron-right

app/views/users/delete_after.html.haml
.exhibit__after
  .exhibit__after__box
    .exhibit__after__box__name
      %p 削除しました
    .exhibit__after__box__text
      %p あなたが出品した商品は「出品した商品一覧」からいつでも見る事ができます。
      = link_to "マイページに戻る", "/users/#{@user.id}" ,class: "exhibit__after__box__next"

app/views/users/edit_item.html.haml
= render "/items/header"

.detail
  .detail_container
    %h1.item_name
      = @item.item_name
    %p.item_about
    -#   『アニエスベー トートバッグ』は、45回の取引実績を持つasaさんから出品されました。アニエスベー（トートバッグ/レディース）の商品で、東京都から4~7日で発送されます。
    .container_wrap
      .item_container
        .item_container__image
          = image_tag @image.url, class: "item_image"
      %table.item_table
        %tr
          %th 出品者
          %td
            = link_to "#{@user.name}", "#",class:"owner_name"
            .evaluation
              %span.user_smile
                =image_tag "logo_smile.png", class: "user_smile"
                117
              = fa_icon ' ', class: 'nomal'
              %span.user_smile
                =image_tag "logo_normal.png", class: "user_smile"
                0
              = fa_icon ' ', class: 'sad'
              %span
                =image_tag "logo_sad.png", class: "user_smile"
                0
        %tr
          %th カテゴリー
          %td
            %p
              = link_to "#{@category.name}", "#"
            %p
              = link_to ">#{@category_c.name}", "#"
            %p
              = link_to ">#{@category_gc.name}", "#"
        %tr
          %th ブランド
          %td
        %tr
          %th 商品の状態
          %td
            = @item.state
        %tr
          %th 配送料の負担
          %td 送料込み(出品者負担)
        %tr
          %th 配送の方法
          %td らくらくメルカリ便
        %tr
          %th 配送元地域
          %td
            = link_to "#", class:"table" do
              = @item.region
        %tr
          %th 発送日の目安
          %td
            = @item.delivery_date
    .item_pricebox
      %span.item_pricebox__price
        = "¥#{@item.price}"
      %span.item_pricebox__tax
        (税込)
      %span.item_pricebox__fee
        送料込み
    .item_description
      = safe_join(@item.description.split("\n"), tag(:br))

  %ul.item_edit_container
    %li.edit
      =link_to "商品の編集","/items/#{@item.id}/edit"
    %p or
    %li
      =link_to "商品の出品を一旦停止する",""
    %li
      =link_to "この商品を削除する","/items/#{@item.id}",method: :delete

  .item_comment_container
    .item_comment_container__info
      相手のことを考え丁寧なコメントを心がけましょう。
      %br 不快な言葉遣いなどは利用制限や退会処分となることがあります。
    %input
    .item_comment_container__btn
      コメントする

= render "/items/footer"

app/views/users/exhibiting.html.haml
= render "/items/header"

.wrapper_mypage
  .wrapper_box
    = render 'side_bar'

    .exhibiting_main
      .exhibiting_main__title
        出品した商品
      .exhibiting_main__middle_menu
        %ul.exhibiting_main__middle_menu__tabs
          %li.menu_item.active
            出品中
          %li.menu_item
            取引中
          %li.menu_item
            売却済

        .exhibiting_main__middle_menu__contents
          %ul
            %li.panel1.show
              - @items.zip(@exhibit_images).each do |item ,image|
                .exhibit__list
                  = image_tag image.url.url, class: "exhibiting_image"
                  .exhibit__list__content__box
                    .exhibit__list__content__box__message
                      = link_to "#{item.item_name}", "edit_item/#{item.id}"
                    .exhibit__list__content__box__time_box
                      %i.fa.fa-heart-o
                      %span
                        = item.goods_count
                      %span.blue_message
                        出品中
                  %i.fa.fa-chevron-right

            %li.panel2
              - @trading_items.zip(@trade_images).each do |item ,image|
                .exhibit__list
                  = image_tag image.url.url, class: "exhibiting_image"
                  .exhibit__list__content__box
                    .exhibit__list__content__box__message
                      = link_to "#{item.item_name}", "trade/#{item.id}"
                    .exhibit__list__content__box__time_box
                      %i.fa.fa-heart-o
                      %span
                        = item.goods_count
                      %span.red_message
                        取引中
                  %i.fa.fa-chevron-right
            %li.panel3
              - @sold_items.zip(@sold_images).each do |item ,image|
                .exhibit__list
                  = image_tag image.url.url, class: "exhibiting_image"
                  .exhibit__list__content__box
                    .exhibit__list__content__box__message
                      = link_to "#{item.item_name}", "sold/#{item.id}"
                    .exhibit__list__content__box__time_box
                      %i.fa.fa-heart-o
                      %span
                        = item.goods_count
                      %span.gray_message
                        売却済
                  %i.fa.fa-chevron-right

= render "/items/footer"

app/views/users/identification.html.haml
= render "/items/header"

.wrapper_mypage
  .wrapper_box
    = render 'side_bar'

    .identification_main
      .identification_main__top
        本人情報の登録
      .identification_main__middle
        .identification_main__middle__info
          お客さまの本人情報をご登録ください。
          %p 登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
        %p
          本人確認書類のアップロードについて >
        .identification_main__middle__form
          .identification_main__middle__form__label
            お名前
          %p
            山田太郎

        .identification_main__middle__form
          .label
            お名前カナ
          %p
            ヤマダタロウ

        .identification_main__middle__form
          .label
            生年月日
          %p
            1982/06/30

        .identification_main__middle__form
          .label
            郵便番号
            %span
              任意
          %input

        .identification_main__middle__form
          .label
            都道府県
            %span
              任意
          %input

        .identification_main__middle__form
          .label
            地区町村
            %span
              任意
          %input

        .identification_main__middle__form
          .label
            番地
            %span
              任意
          %input

        .identification_main__middle__form
          .label
            建物名
            %span
              任意
          %input

        .identification_main__middle__btn
          =link_to '登録する'

= render "/items/footer"

app/views/users/logout.html.haml
= render "/items/header"

.wrapper_mypage
  .wrapper_box
    = render 'side_bar'
    .main_box
      .main_box__container
        .main_box__container__btn
          =link_to 'ログアウト', destroy_user_session_path, method: :delete

= render "/items/footer"

app/views/users/profile.html.haml
= render "/items/header"

.wrapper_mypage
  .wrapper_box
    = render 'side_bar'

    .profile_main
      .profile_main__top
        プロフィール
      .profile_main__middle
        = image_tag "avatar.png",class:"profile_main__middle__image"
        .profile_main__middle__nickname
          = current_user.name
      .profile_main__bottom
        = form_for [@user] do |f|
          = f.text_area :profile, value:@user.profile, placeholder: "例）こんにちは☆ご覧いただきありがとうございます！かわいいものやきれいめオフィスカジュアル中心に出品しています。服のサイズは主に9号です。気持ちよくお取引できるよう心がけていますので、商品や発送方法などご質問がありましたらお気軽にどうぞ♪",class: "profile_main__bottom__introduce"
          = f.submit "変更する",class:"profile_main__bottom__btn"

= render "/items/footer"

app/views/users/show.html.haml
= render "/items/header"

.wrapper_mypage
  .wrapper_box
    = render 'side_bar'

    .main
      .main__top_contents
        =image_tag "mypage_background.jpg"
        .main__top_contents__box
          = image_tag "avatar.png",class:"main__top_contents__box__image"
          .main__top_contents__box__nickname
            = current_user.name
          .main__top_contents__box__status
            .main__top_contents__box__status__evaluation
              評価
              %span
                33
            .main__top_contents__box__status__exhibits
              出品数
              %span
                58
      .main__middle_menu
        .main__middle_menu__tabs
          %p.infomation
            お知らせ
          %p.to_do
            やることリスト
        .main__middle_menu__list
          %ul
            %li.main__middle_menu__list__content
              =image_tag "mypage_logo.png", class: "main__middle_menu__list__mercari_logo"
              .main__middle_menu__list__box
                .main__middle_menu__list__message
                  事務局から個別メッセージ「Googleログイン通知」
                .main__middle_menu__list__time_box
                  %i.fa.fa-clock-o#i1
                  %span
                    5 時間前
              %i.fa.fa-chevron-right
            %li.main__middle_menu__list__content
              =image_tag "mypage_logo.png", class: "main__middle_menu__list__mercari_logo"
              .main__middle_menu__list__box
                .main__middle_menu__list__message
                  事務局から個別メッセージ「Googleログイン通知」
                .main__middle_menu__list__time_box
                  %i.fa.fa-clock-o
                  %span
                    5 時間前
              %i.fa.fa-chevron-right
            %li.main__middle_menu__list__content
              =image_tag "mypage_logo.png", class: "main__middle_menu__list__mercari_logo"
              .main__middle_menu__list__box
                .main__middle_menu__list__message
                  事務局から個別メッセージ「Googleログイン通知」
                .main__middle_menu__list__time_box
                  %i.fa.fa-clock-o
                  %span
                    5 時間前
              %i.fa.fa-chevron-right
            %li.main__middle_menu__list__content
              =image_tag "mypage_logo.png", class: "main__middle_menu__list__mercari_logo"
              .main__middle_menu__list__box
                .main__middle_menu__list__message
                  事務局から個別メッセージ「Googleログイン通知」
                .main__middle_menu__list__time_box
                  %i.fa.fa-clock-o
                  %span
                    5 時間前
              %i.fa.fa-chevron-right
            %li.main__middle_menu__list__content
              =image_tag "mypage_logo.png", class: "main__middle_menu__list__mercari_logo"
              .main__middle_menu__list__box
                .main__middle_menu__list__message
                  事務局から個別メッセージ「Googleログイン通知」
                .main__middle_menu__list__time_box
                  %i.fa.fa-clock-o
                  %span
                    5 時間前
              %i.fa.fa-chevron-right
            %li.go_mypage_list
              %p
                一覧を見る
      .main__bottom_menu
        .main__bottom_menu__title
          購入した商品
        .main__bottom_menu__tabs
          %p.transaction_now
            取引中
          %p.transaction_before
            過去の取引

= render "/items/footer"

app/views/users/sold.html.haml
= render "/items/header"

.wrapper_mypage
  .wrapper_box
    = render 'side_bar'

    .trade_main
      .trade_main__top
        取引画面
      .trade_main__middle
        .trade_main__middle__message
          %i.fa.fa-check
          %span
            取引きが完了しました
        .trade_main__middle__info
          このたびはメルカリのご利用ありがとうございました
      .trade_main__line
        販売代金の受け取りについて ＞
      .trade_main__bottom
        .trade_main__bottom__btn_sold
          =link_to 'この商品を削除する',"/items/#{@item.id}",method: :delete
      .trade_main__last_message
        取引完了後、２週間経過または最新取引メッセージから２週間経過したため、取引メッセージを非公開にしました。

= render "/items/footer"

app/views/users/trade.html.haml
= render "/items/header"

.detail
  .detail_container
    %h1.item_name
      = @item.item_name
    %p.item_about
    -#   『アニエスベー トートバッグ』は、45回の取引実績を持つasaさんから出品されました。アニエスベー（トートバッグ/レディース）の商品で、東京都から4~7日で発送されます。
    .container_wrap
      .item_container
        .item_container__image
          = image_tag @image.url, class: "item_image"
      %table.item_table
        %tr
          %th 出品者
          %td
            = link_to "#{@user.name}", "/users/#{@user.id}",class:"owner_name"
            .evaluation
              %span.user_smile
                =image_tag "logo_smile.png", class: "user_smile"
                117
              = fa_icon ' ', class: 'nomal'
              %span.user_smile
                =image_tag "logo_normal.png", class: "user_smile"
                0
              = fa_icon ' ', class: 'sad'
              %span
                =image_tag "logo_sad.png", class: "user_smile"
                0
        %tr
          %th カテゴリー
          %td
            %p
              = link_to "#{@category.name}", "#"
            %p
              = link_to ">#{@category_c.name}", "#"
            %p
              = link_to ">#{@category_gc.name}", "#"
        %tr
          %th ブランド
          %td
        %tr
          %th 商品の状態
          %td
            = @item.state
        %tr
          %th 配送料の負担
          %td 送料込み(出品者負担)
        %tr
          %th 配送の方法
          %td らくらくメルカリ便
        %tr
          %th 配送元地域
          %td
            = link_to "#", class:"table" do
              = @item.region
        %tr
          %th 発送日の目安
          %td
            = @item.delivery_date
    .item_pricebox
      %span.item_pricebox__price
        = "¥#{@item.price}"
      %span.item_pricebox__tax
        (税込)
      %span.item_pricebox__fee
        送料込み
    - if @trading.sale_state == "exhibit"
      .item_buy
        = link_to "購入画面に進む", item_buy_path(@item), class: ""
    - else
      .sold_item__btn
        %p 売り切れました
    .item_description
      = safe_join(@item.description.split("\n"), tag(:br))
    .item_btn_container
      .item_btn_container__btn_like
        %span.item_btn_like__icon_heart
          ♡
        %span.item_btn_like__btn_like
          いいね
        %span.item_btn_like__like_num
          46
      .item_btn_container__btn_report
        %span.item_btn_report__icon_flag
          ▷
        %span.item_btn_report__btn_report
          不適切な商品の報告
      .item_btn_container__btn_declaration
        %span.item_btn_declaration__icon_lock
          ◇
        %span.item_btn_declaration__btn_lock
          あんしん・あんぜんへの取り組み

  .trade_bottom
    .trade_bottom__top
      取引画面
    .trade_bottom__middle
      .trade_bottom__middle__message
        %i.fa.fa-truck
        %span
          商品を発送してください
      .trade_bottom__middle__info
        商品が購入され支払いされました。商品の発送を行ってください。
    .trade_bottom__line
      商品が売れた後の流れ ＞
    .trade_bottom__bottom
      = form_for @trading, url:"/items/#{@item.id}",method: :patch do |f|
        = f.submit "商品の発送をしたので、発送通知をする", class: "trade_bottom__bottom__btn"
    .trade_bottom__last_message
      取引完了後、２週間経過または最新取引メッセージから２週間経過したため、取引メッセージを非公開にしました。

= render "/items/footer"

app/views/users/trade_after.html.haml
= render "/items/header"

.wrapper_mypage
  .wrapper_box
    = render 'side_bar'

    .trade_main
      .trade_main__top
        取引画面
      .trade_main__middle
        .trade_main__middle__message
          %i.fa.fa-check
          %span
            商品の発送を通知しました
        .trade_main__middle__info
          商品の発送には平均で2〜4日かかります。購入者からの受取評価をお待ちください。
      .trade_main__line
      .trade_main__bottom
        .trade_main__bottom__btn
          =link_to '出品した商品に戻る',"/users/#{@user.id}/exhibiting"
= render "/items/footer"