config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root "items#index"

  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      post 'step2'
      get 'step3'
      post 'step3'
      get 'step4'
      get "/jip" => "signup#jip"
      post 'create_step4' => "signup#create_step4"
      get 'step5'
      get 'set'
      get 'done'
    end
  end

  resources :items do
    resources :good, only: [:create, :destroy]
    get "buy" => "items#buy"
    collection do
      get 'category_children', defaults: { format: 'json' }
      get "category_grandchildren", defaults: { format: "json"}
      get "search"
      get "search_more"
    end
  end

  resources :items ,only: [:edit] do
    member do
      get 'category_children', defaults: { format: 'json' }
      get "category_grandchildren", defaults: { format: "json"}
    end
    patch "edit_update" => "items#edit_update"
  end

  get "more/:id" => "items#more"
  get "buy_after" => "items#buy_after"

  resources :users do
    get "edit_item/:id" => "users#edit_item"
    get "logout" => "users#logout"
    get "profile" => "users#profile"
    get "exhibiting" => "users#exhibiting"
    get "identification" => "users#identification"
    get "trade/:id" => "users#trade"
    get "trade_after" => "users#trade_after"
    get "sold/:id" => "users#sold"
  end

  resources :credit_cards do
    collection do
      post 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end

  resources :purchase, only: [:index] do
    collection do
      get 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end

end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :item, counter_cache: :goods_count
  belongs_to :user
end

app/controllers/good_controller.rb
class GoodController < ApplicationController
  def create
    @good = Good.create(user_id: current_user.id, item_id: params[:item_id])
    @goods = Good.where(item_id: params[:item_id])
    @item = Item.find(params[:item_id])
  end

  def destroy
    good = Good.find_by(user_id: current_user.id, item_id: params[:item_id])
    good.destroy
    @goods = Good.where(item_id: params[:item_id])
    @item = Item.find(params[:item_id])
  end
end

app/helpers/good_helper.rb
module GoodHelper
end

app/views/good/_good.html.erb
<% if user_signed_in? %>

  <% if item.good_user(current_user.id) %>
    <%= link_to item_good_path(good, item_id: item.id), method: :delete, id: "good-button", remote: true do %>
    <button class="item__goods good_now">
      <div class="item_btn_container__btn">
        <span class="item_btn_like__icon_heart good_now_heart">
          <i class="fa fa-heart "></i>
        </span>
        <span class="item_btn_like__btn_like">
          いいね済
        </span>
        <span class="item_btn_like__like_num">
          <%= item.goods_count %>
        </span>
      </div>
    </button>
    <% end %>

  <% else %>
    <%= link_to item_good_index_path(item.id), method: :post, id: "good-button", class:"good_btn", remote: true do %>
    <button class="item__goods">
      <div class="item_btn_container__btn">
        <span class="item_btn_like__icon_heart">
          ♡
        </span>
        <span class="item_btn_like__btn_like">
          いいね
        </span>
        <span class="item_btn_like__like_num">
          <%= item.goods_count %>
        </span>
      </div>
    </button>
    <% end %>
  <% end %>

<% else %>
  <div class="item_btn_container__btn">
    <span class="item_btn_like__icon_heart">
      ♡
    </span>
    <span class="item_btn_like__btn_like">
      いいね
    </span>
    <span class="item_btn_like__like_num">
      <%= item.goods_count %>
    </span>
  </div>
<% end %>

app/views/good/create.js.erb
$("#good-button").html("<%= j(render partial: 'good', locals: {item: @item, good: @goods}) %>");

app/views/good/destroy.js.erb
$("#good-button").html("<%= j(render partial: 'good', locals: {item: @item, good: @goods}) %>");