config/routes.rb
Rails.application.routes.draw do

  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root "items#index"

  resources :signup do
    collection do
      get 'step1'
      get 'step2'
      post 'step2'
      get 'step3'
      post 'step3'
      get 'step4'
      get "/jip" => "signup#jip"
      post 'create_step4' => "signup#create_step4"
      get 'step5'
      get 'set'
      get 'done'
    end
  end

  resources :items do
    resources :good, only: [:create, :destroy]
    get "buy" => "items#buy"
    collection do
      get 'category_children', defaults: { format: 'json' }
      get "category_grandchildren", defaults: { format: "json"}
      get "search"
      get "search_more"
    end
  end

  resources :items ,only: [:edit] do
    member do
      get 'category_children', defaults: { format: 'json' }
      get "category_grandchildren", defaults: { format: "json"}
    end
    patch "edit_update" => "items#edit_update"
  end

  get "more/:id" => "items#more"
  get "buy_after" => "items#buy_after"

  resources :users do
    get "edit_item/:id" => "users#edit_item"
    get "logout" => "users#logout"
    get "profile" => "users#profile"
    get "exhibiting" => "users#exhibiting"
    get "identification" => "users#identification"
    get "trade/:id" => "users#trade"
    get "trade_after" => "users#trade_after"
    get "sold/:id" => "users#sold"
  end

  resources :credit_cards do
    collection do
      post 'show', to: 'credit_cards#show'
      post 'pay', to: 'credit_cards#pay'
      post 'delete', to: 'credit_cards#delete'
    end
  end

  resources :purchase, only: [:index] do
    collection do
      get 'index', to: 'purchase#index'
      post 'pay', to: 'purchase#pay'
      get 'done', to: 'purchase#done'
    end
  end

end

app/models/item.rb
class Item < ApplicationRecord

  has_one :trading, dependent: :destroy
  has_one :categories
  has_many :images, dependent: :destroy
  has_many :goods, dependent: :destroy

  def good_user(user_id)
    goods.find_by(user_id: user_id)
  end

  validates :item_name, presence: true, length: { in: 1..40 }
  validates :description, presence: true, length:{maximum: 1000 , message: "must be given please" }
  validates :price, numericality: { only_integer: true, greater_than_or_equal_to:300, less_than:9999999 }
  validates :category_index,presence:true
  validates :state, presence: true
  validates :fee_size, presence: true
  validates :region, presence: true
  validates :delivery_date, presence: true
  validates :category_index, exclusion: { in: %w(---) }

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show, :more, :search, :search_more]
  before_action :pull
  before_action :set_item, only: [:show, :edit, :destroy]

  def index
    la_query = "select * from items join tradings on items.id = item_id where tradings.sale_state = 'exhibit' and category_index between 1 and 137 order by items.created_at desc limit 10"
    @ladies_items = Item.find_by_sql(la_query)
    la_item_id = Trading.where(id: @ladies_items.map{|a| a[:id]}).map{|a| a[:item_id]}
    @la_image = Image.where(item_id: la_item_id).order("created_at desc")

    me_query = "select * from items join tradings on items.id = item_id where tradings.sale_state = 'exhibit' and category_index between 138 and 258 order by items.created_at desc limit 10"
    @mens_items = Item.find_by_sql(me_query)
    me_item_id = Trading.where(id: @mens_items.map{|a| a[:id]}).map{|a| a[:item_id]}
    @me_image = Image.where(item_id: me_item_id).order("created_at desc")

    ma_query = "select * from items join tradings on items.id = item_id where tradings.sale_state = 'exhibit' and category_index between 781 and 866 order by items.created_at desc limit 10"
    @machine_items = Item.find_by_sql(ma_query)
    ma_item_id = Trading.where(id: @machine_items.map{|a| a[:id]}).map{|a| a[:item_id]}
    @ma_image = Image.where(item_id: ma_item_id).order("created_at desc")

    ho_query = "select * from items join tradings on items.id = item_id where tradings.sale_state = 'exhibit' and category_index between 576 and 682 order by items.created_at desc limit 10"
    @hobby_items = Item.find_by_sql(ho_query)
    ho_item_id = Trading.where(id: @hobby_items.map{|a| a[:id]}).map{|a| a[:item_id]}
    @ho_image = Image.where(item_id: ho_item_id).order("created_at desc")
  end

  def new
    @item = Item.new
    @category_array = ["---"]
    Category.where(ancestry: nil).each do |parent|
      @category_array << parent.name
    end
  end

  def buy
    @user = User.find(current_user.id)
    @item = Item.find(params[:item_id])
    @trading = Trading.find_by(item_id: "#{params[:item_id]}")
    @image = Image.find_by(item_id: @item.id).url
    @delivery = Delivery.find_by(user_id: current_user.id)
    @card = CreditCard.find_by(user_id: current_user.id)

    Payjp.api_key = 'sk_test_f98999ddca480c61d3498ee7'
    customer = Payjp::Customer.retrieve(@card.customer_id,)
    @default_card_information = customer.cards.retrieve(@card.card_id)
  end

  def update
    @trading = Trading.find_by(item_id: "#{params[:id]}")
    if @trading.sale_state == "trade"
      @trading.update(sale_state: "sold")
      redirect_to "/users/#{current_user.id}/trade_after"
    end
  end

  def show
    @category_gc= Category.find(@item[:category_index])
    @category_c = @category_gc.parent
    @category = @category_c.parent
    @trading = Trading.find_by(item_id: params[:id])
    @user = User.find(@trading.saler_id)
    @good = Good.where(item_id: params[:id])
    @image = Image.find_by(item_id: params[:id]).url

    category_id = Category.where("ancestry like ?", "#{@category.id}/%")
    @item_list = Item.where(category_index: category_id).limit(6).order("created_at desc").where.not(id: params[:id])
    item_id = @item_list.map{|a| a[:id]}
    @trade_list = Trading.where(item_id: item_id).order("created_at desc")
    @image_list = Image.where(item_id: item_id).order("created_at desc")
  end

  def create
    @item = Item.new(item_name: item_params[:item_name],
                description: item_params[:description],
                price: item_params[:price],
                state: item_params[:state],
                size: item_params[:size],
                fee_size: item_params[:fee_size],
                region: item_params[:region],
                delivery_date: item_params[:delivery_date],
                category_index: item_params[:category_index])
    @item.build_trading(saler_id: current_user.id)
    @category_array = ["---"]
    Category.where(ancestry: nil).each do |parent|
      @category_array << parent.name
    end

    @item.images.build(url: item_params[:url])
    if @item.save
      # redirect_to new_after_path
    else
      flash[:category_alert] = "カテゴリーを選択してください"
      flash[:img_alert] = "画像を添付してください"
      render action: :new
    end
  end

  def destroy
    render action: :edit unless @item.destroy
  end

  def edit
    @user = User.find(current_user.id)

    @category_array = ["---"]
    Category.where(ancestry: nil).each do |parent|
      @category_array << parent.name
    end
  end

  def edit_update
    @item = Item.find(params[:item_id])
    @item.update(item_name: item_params[:item_name], description: item_params[:description],
                price: item_params[:price], state: item_params[:state],
                size:item_params[:size], fee_size: item_params[:fee_size],
                region: item_params[:region],
                delivery_date: item_params[:delivery_date],
                category_index: item_params[:category_index])
    @category_array = ["---"]
    Category.where(ancestry: nil).each do |parent|
      @category_array << parent.name
    end

    if @item.save
      redirect_to "/users/#{current_user.id}"
    else
      render action: :edit
    end
  end


  def more
    @category_gc = Category.find(params[:id])
    @category_c = nil
    @parent = nil

    if (@category_gc[:ancestry] == nil)       #第1世代を引いた時
      @parent = @category_gc
      @category_gc = nil
      category_id = Category.where("ancestry like ?", "#{@parent.id}/%")
      @category_list = @parent.children
      @item_list = Item.where(category_index: category_id).order("created_at desc")

    elsif (@category_gc[:ancestry].match("\/"))       #第3世代を引いたとき
      @category_c = @category_gc.parent
      @parent = @category_c.parent
      @item_list = Item.where(category_index: @category_gc).order("created_at desc")

    elsif (@category_gc.children != nil) && (@category_gc.parent != nil)   #第2世代を引いた時
      @category_c = @category_gc
      @parent = @category_gc.parent
      @category_gc = nil
      @items = Item.where(category_index: @category_c)
      @category_list = @category_c.children
      category_id = @category_list.map{|i| i.id}
      @item_list = Item.where(category_index: category_id).order("created_at desc")
    end

    item_id = @item_list.map{|a| a[:id]}
    @trade = Trading.where(item_id: item_id).order("created_at desc")
    @image = Image.where(item_id: item_id).order("created_at desc")
  end

  def category_children
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  def category_grandchildren
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def pull
    @parents = Category.where(ancestry: nil)
  end

  def set_item
    @item = Item.find(params[:id])
  end

  def search
    input = params[:search].to_s
    if input.length != 0
      @items = Item.where(' item_name LIKE(?) or description LIKE(?)', "%#{input}%", "%#{input}%").order("created_at desc")
      if @items.length == 0
        redirect_to root_path, flash: {search_alert: "検索結果がありませんでした"}
      else
        @images = Image.where(item_id: @items.map{|i| i.id}).order("created_at desc")
        @trade = Trading.where(item_id: @items.map{|i| i.id}).order("created_at desc")
      end
    else
      redirect_to root_path, flash: {search_alert: "検索結果がありませんでした"}
    end
    @q = Item.ransack(params[:q])
    # @items = @q.result(distinct: true)
  end

  def search_more
    @item_name = params[:q][:item_name_cont]
    if params[:q][:category_index_in] !=  ""
      params[:q][:category_index_in] = Category.find(params[:q][:category_index_in]).descendant_ids
    end
    @q = Item.ransack(params[:q])
    @items = @q.result(distinct: true).order("created_at desc")
    if @items == []
      redirect_to root_path, flash: {search_alert: "検索結果がありませんでした"}
    end
    @images = Image.where(item_id: @items.map{|i| i.id}).order("created_at desc")
    @trade = Trading.where(item_id: @items.map{|i| i.id}).order("created_at desc")
  end

  private

  def item_params
    params.require(:item).permit(:item_name, :description, :price, :state, :size, :fee_size, :region, :delivery_date, :category_index, :url, :item_name_cont)
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_error_messages.html.haml
- if item.errors.any?
  - unless item.valid?
    - if errors = item.errors.full_messages_for(column.to_sym)
      .alert
        %ul
          - errors.each do |error|
            %li=error

app/views/items/_footer.html.haml
%footer
  .footer
    .footer__upper
      =image_tag "footer_img.png", class: "footer__img"
      .fortunetelling
    .footer__mid
      .footer__list__about
        %h2 メルカリについて
        %ul.no_circle
          %li 会社概要（運営会社）
          %li 採用情報
          %li プレスリリース
          %li 公式ブログ
          %li メルカリロゴ利用ガイドライン
          .footer__logo__sns
            =link_to "https://twitter.com/mercari_jp" do
              %i.fa.fa-twitter
            =link_to "https://www.facebook.com/mercarijp" do
              %i.fa.fa-facebook-square

      .footer__list__guide
        %h2 ヘルプ＆ガイド
        %ul.no_circle
          %li メルカリガイド
          %li らくらくメルカリ便
          %li ゆうゆうメルカリ便
          %li 大型メルカリ便
          %li 車体取引ガイド
          %li メルカリあんしん・あんぜん宣言！
          %li 偽ブランド品撲滅への取り組み
          %li メルカリボックス
      ​
      .footer__list__privacy_and_rule
        %h2 プライバシーと利用規約
        .footer__list__privacy
          %ul.no_circle
            %li プライバシーポリシー
            %li メルカリ利用規約
            %li あんしんスマホサポート制度に関する利用特約
            %li コンプライアンスポリシー
        ​
      .footer__list__rule
        %h2{ style: "color:rgb(34,34,34)" }٩(๑❛ᴗ❛๑)۶
        %ul.no_circle
          %li 個人データの安全管理に係る基本方針
          %li 特定商取引に関する表記
          %li 資金決済法に基づく表示
          %li 法令順守と犯罪抑止のために
        ​
      .footer__list__country
        %h2 国
        %ul.no_circle
          %li 日本
          %li United States

    .footer__lower
      =link_to "/" do
        =image_tag "top_footer_logo.png", class: "footer__logo logo"
      %span.footer__copyright © 2019 Mercari

app/views/items/_header.html.haml
%header
  .wrap
    .header_top
      =link_to root_path do
        =image_tag "header_logo.png", class: "header_logo logo"
      = form_tag(search_items_path, method: :get, class: 'header_search') do
        - if flash[:search_alert]
          = text_field_tag :search ,"", class: "header_search_field", placeholder: flash[:search_alert]
        - else
          = text_field_tag :search ,"", class: "header_search_field", placeholder: "何かお探しですか？"
        = button_tag type: 'submit', class:"header_search_button" do
          %i.fa.fa-search

    .header_bottom
      .header_nav
        .header_nav_category
          =image_tag "tag1.png", class: "header__icon"
          %span カテゴリーから探す
        = render "items/pulldown"
        .header_nav_brand
          =image_tag "tag2.png", class: "header__icon"
          %span ブランドから探す
        .header_nav_brand_lists
          %ul
            %li シャネル
            %li ナイキ
            %li ルイ ヴィトン
            %li シュプリーム
            %li アティダス
            %li ブランド一覧
      .header_ragistration
        - if user_signed_in?
          .header_ragistration_banner
            = link_to "/" do
              %i.fa.fa-heart-o
              %span いいね！一覧
            = link_to "/" do
              %i.fa.fa-bell-o
              %span.mf お知らせ
            = link_to "/" do
              %i.fa.fa-check
              %span やることリスト
            = link_to "/users/1" do
              = image_tag "avatar.png",class:"header_avatar"
              %span マイページ
        - else
          = link_to "新規会員登録", new_user_registration_path, class: 'header_sign_up'
          = link_to "ログイン", new_user_session_path, class: 'header__sign_in'

app/views/items/_pulldown.html.haml
.header__nav
  .header__menu
  .header__puru
    %ul.parent_box
      - @parents.each do |p|
        %li.parent_list
          = link_to "#{p.name}", "/more/#{p.id}"
          %ul.children_box
            - p.children.each do |c|
              %li.children_list
                = link_to "#{c.name}", "/more/#{c.id}"
                %ul.grandchildren_box
                  - c.children.each do |gc|
                    %li.grandchildren_list
                      = link_to "#{gc.name}", "/more/#{gc.id}"

app/views/items/buy.html.haml
.sign_in__page
  .registration__header__logo
    =link_to root_path do
      =image_tag "header_logo.png", class: "logo"

.registration__first
  .registration__first__box
    %h2.registration__first__box__top
      %p.edit__top__title 購入内容の確認
    .edit__top
      .edit__top__box
        .edit__top__box__detail
          .edit__top__box__detail__img
            = image_tag @image.url, class: "buy_image"
          %p
            = @item.item_name
        .edit__top__box__price
          %p
            = "¥#{@item.price}"
            %span
              送料込み
        .edit__top__box__point
          %p ポイントはありません
        .edit__top__box__pay
          %p 支払い金額
          %p
            = "¥#{@item.price}"
        .edit__top__box__buy

          = link_to pay_purchase_index_path(@item),method: :post do
            %button 購入する

    .edit__middle
      .edit__middle__box
        %p 配送先
        .edit__middle__box__address
          %p 〒 #{@delivery.postal_code}
          %p #{@delivery.area} #{@delivery.city} #{@delivery.address}
          %p #{@delivery.building}
          %p #{@user.name}
        = link_to "変更する >","#"

    .edit__bottom
      .edit__bottom__box
        %p 支払い方法
        .edit__bottom__box__pay
          %p= "**** **** **** " + @default_card_information.last4
          - exp_month = @default_card_information.exp_month.to_s
          - exp_year = @default_card_information.exp_year.to_s.slice(2,3)
          %p= exp_month + " / " + exp_year
          %p VISA
        = link_to "変更する >", "#"

  = render partial: "devise/layout/footer"

app/views/items/create.html.haml
.exhibit__after
  .exhibit__after__box
    .exhibit__after__box__name
      %p 出品が完了しました
    .exhibit__after__box__text
      %p あなたが出品した商品は「出品した商品一覧」からいつでも見る事ができます。
      = link_to new_item_path class: "exhibit__after__box__next" do
        %p 続けて出品する
      %p 商品ページへ行ってシェアする

app/views/items/destroy.html.haml
.exhibit__after
  .exhibit__after__box
    .exhibit__after__box__name
      %p 削除しました
    .exhibit__after__box__text
      %p あなたが出品した商品は「出品した商品一覧」からいつでも見る事ができます。
      = link_to "マイページに戻る", "/users/#{current_user.id}" ,class: "exhibit__after__box__next"

app/views/items/edit.html.haml
.exhibit__main

  .registration__header__logo
    =link_to "/" do
      =image_tag "header_logo.png", class: "logo"
  .exhibit__contents
    .exhibit__infomation
      %p 商品の情報を入力

    = form_for(@item, url: item_edit_update_path(@item)) do |f|
      .exhibit__upload
        .exhibit__upload_head
          %p 出品画像
          %span.exhibit_span 必須
        %p 最大10枚までアップロードできます
        .exhibit__upload_image
          %label
            %div.exhibit__upload_image_field
              %p ドラッグアンドドロップ
              %p またはクリックしてファイルをアップロード

      .exhibit__explanation
        .exhibit__explanation__title
          .exhibit__explanation__title_head
            %p  商品名
            %span.exhibit_span 必須
          .exhibit__explanation__title_field
            = f.text_field :item_name, placeholder: "商品名（必須 40文字まで)", maxlength: 40, class: "item_name_form"
            = render partial: 'error_messages', locals: {item: @item, column: "item_name"}

        .exhibit__explanation__detail
          .exhibit__explanation__detail_head
            %p  商品の説明
            %span.exhibit_span 必須
          .exhibit__explanation__detail_field
            = f.text_area :description, placeholder: "商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", class: "description_name_form"
            = render partial: 'error_messages', locals: {item: @item, column: "description"}

      .exhibit__detail.clearfix
        %p 商品の詳細
        .exhibit__detail__container
          .exhibit__detail__container__title
            .exhibit__detail__container__title__category
              = f.label "カテゴリー"
              %span.exhibit_span 必須
              .exhibit__detail__container__title_field
                = f.select :category_index, @category_array, {}, {class: "select-default", id: "chose-category"}
                = render partial: 'error_messages', locals: {item: @item, column: "category"}

            .exhibit__detail__container__title__shoes
              = f.label "サイズ"
              %span.exhibit_span 必須
              .exhibit__detail__container__title__shoes__chose
                = f.select :size, [["---",""], ["20cm以下", "20cm以下"], ["20.5cm", "20.5cm"], ["21cm", "21cm"],
                                  ["21.5cm", "21.5cm"], ["22cm", "22cm"], ["22.5cm", "22.5cm"], ["23cm", "23cm"],
                                  ["23.5cm", "23.5cm"], ["24cm", "24cm"], ["24.5cm", "24.5cm"], ["25cm", "25cm"],
                                  ["25.5cm", "25.5cm"], ["26cm", "26cm"], ["26.5cm", "26.5cm"], ["27cm", "27cm"], ["27.5cm以上", "27.5cm以上"]], {}, {class: "select-default"}

          .exhibit__detail__container__detail
            .exhibit__detail__container__detail_head
              %p  商品の状態
              %span.exhibit_span 必須
            .exhibit__detail__container__detail_field
              = f.select :state, [["---",""],["新品、未使用", "新品、未使用"],
                                  ["未使用に近い", "未使用に近い"], ["目立った傷や汚れなし", "目立った傷や汚れなし"],
                                  ["やや傷や汚れあり", "やや傷や汚れあり"], ["傷や汚れあり", "傷や汚れあり"],
                                  ["全体的に状態が悪い", "全体的に状態が悪い"]],{}, {class: "select-default"}
              %br
              = render partial: 'error_messages', locals: {item: @item, column: "state"}

      .exhibit__delivery.clearfix
        %p 配送について
        .exhibit__delivery__container
          .exhibit__delivery__container__fee
            .exhibit__delivery__container__fee_head
              %p  配送料の負担
              %span.exhibit_span 必須
            .exhibit__delivery__container__fee_field
              = f.select :fee_size, [["---",""], ["送料込み(出品者負担)", "送料込み(出品者負担)"],
                                    ["着払い(購入者負担)", "着払い(購入者負担)"]],{}, {class: "select-default"}
              %br
              = render partial: 'error_messages', locals: {item: @item, column: "fee_size"}

          .exhibit__delivery__container__shipping_region
            .exhibit__delivery__container__shipping_region_head
              %p  発送元の地域
              %span.exhibit_span 必須
            .exhibit__delivery__container__shipping_region_field
              = f.collection_select :region, Prefecture.all, :id, :name, {prompt: "---"}, {class: "select-default"}
              %br
              = render partial: 'error_messages', locals: {item: @item, column: "region"}

          .exhibit__delivery__container__day
            .exhibit__delivery__container__day_head
              %p  発送までの日数
              %span.exhibit_span 必須
            .exhibit__delivery__container__day_field
              = f.select :delivery_date, [["---", ""], ["1~2日で発送", "1~2日で発送"],
                                          ["2~3日で発送", "2~3日で発送"], ["4~7日で発送", "4~7日で発送"]],{}, {class: "select-default"}
              %br
              = render partial: 'error_messages', locals: {item: @item, column: "delivery_date"}

      .exhibit__price.clearfix
        %span 販売価格(300~9,999,999)
        .exhibit__price__container
          .exhibit__price__container__fee.clearfix
            .exhibit__price__container__fee_head
              %p  価格
              %span.exhibit_span 必須
              %br
            .exhibit__price__container__fee_field
              %span ¥
              = f.text_field :price, placeholder: "例）300",class:"price_form"
              %br
              = render partial: 'error_messages', locals: {item: @item, column: "price"}

          .exhibit__price__container__sale_fee.clearfix
            .exhibit__price__container__sale_fee_head
              %span  販売手数料(10%)
              %p.exhibit_tax -
          .exhibit__price__container__sale_profit.clearfix
            .exhibit__price__container__sale_profit_head
              %span  販売利益
              %p.exhibit_profit -
      .exhibit__confirmation
        .exhibit__confirmation__article
          %p 禁止されている出品、行為を必ずご確認ください。
          %p またブランド品でシリアルナンバー等がある場合はご記載ください。偽ブランドの販売は犯罪であり処罰される可能性があります。
          %p また、出品をもちまして加盟店規約に同意したことになります。
        .exhibit__confirmation__button__display
          = f.submit "変更する"
        .exhibit__confirmation__button__back
          %a( href='')戻る

  = render partial: "devise/layout/footer"

app/views/items/new_after.html.haml
.exhibit__after
  .exhibit__after__box
    .exhibit__after__box__name
      %p 出品が完了しました
    .exhibit__after__box__text
      %p あなたが出品した商品は「出品した商品一覧」からいつでも見る事ができます。
      =link_to new_item_path class: "exhibit__after__box__next" do
        %p 続けて出品する
      %p 商品ページへ行ってシェアする

app/views/items/regi_fifth.html.haml
.registration__header

.registration__first
  .registration__first__box
    %h2.registration__first__box__top 支払い方法
    %form.registration__first__box__middle{action: "#"}
      .registration__first__box__middle__input
        .registration__first__box__middle__input__name 
          カード番号
          %span 必須
        %input{placeholder: "  半角数字のみ"}
        =image_tag "card_list.png", class: "card_list"
      .registration__first__box__middle__input
        .registration__first__box__middle__input__name 
          有効期限
          %span 必須
        .registration__first__box__middle__input__double__card
          %select
            %option 01
            %option 02
            %option 03
            %option 04
            %option 05
            %option 06
            %option 07
            %option 08
            %option 09
            %option 10
            %option 11
            %option 12
          %span 月
          %select
            %option 19
            %option 20
            %option 21
            %option 22
            %option 23
            %option 24
            %option 25
            %option 26
            %option 27
            %option 28
            %option 29
          %span 年
      .registration__first__box__middle__input
        .registration__first__box__middle__input__name 
          セキュリティコード
          %span 必須
        %input{placeholder: "  カード背面4桁もしくは3桁の番号"}
        %a{href: "#"} カード裏面の番号とは？
        %button{type: "submit", onclick: "location.href='#"} 次へ進む

  = render partial: "devise/layout/footer"

app/views/items/search.html.haml
= render "header"

.main_contents
  .main_contents__box
    .main_contents__box__contents__search
      .main_contents__box__contents__search__left
        = search_form_for @q, url: search_more_items_path do |f|
          .search__list
            %h3 詳細検索
            .search__list__detail
              = f.label :item_name_or_description, "キーワードを追加する"
              = f.search_field :item_name_or_description_cont, class: "search-more-default"

            .search__list__detail
              = f.label :category_index, "カテゴリーを選択する"
              = f.collection_select :category_index_in, Category.where(ancestry:nil), :id, :name, include_blank: "---"

            .search__list__detail
              = f.label :price, "価格"
              .search__list__detail__price
                = f.number_field :price_gteq, placeholder:"￥Min", class: "price-select"
                %span ~
                = f.number_field :price_lt, placeholder:"￥Max", class: "price-select"

            .search__list__detail
              = f.label :state, "商品の状態"
              .search__list__detail__state_box
                .search__list__detail__state_box__one
                  = f.radio_button :state_eq,  '', {:checked => true}
                  %span すべて
                .search__list__detail__state_box__one
                  = f.radio_button :state_eq, '新品、未使用'
                  %span 新品、未使用
                .search__list__detail__state_box__one
                  = f.radio_button :state_eq, '未使用に近い'
                  %span 未使用に近い
                .search__list__detail__state_box__one
                  = f.radio_button :state_eq, '目立った傷や汚れなし'
                  %span 目立った傷や
                  %br 汚れなし
                .search__list__detail__state_box__one
                  = f.radio_button :state_eq, 'やや傷や汚れあり'
                  %span やや傷や汚れ
                  %br あり
                .search__list__detail__state_box__one
                  = f.radio_button :state_eq, '傷や汚れあり'
                  %span 傷や汚れあり
                .search__list__detail__state_box__one
                  = f.radio_button :state_eq, '全体的に状態が悪い'
                  %span 全体的に状態
                  %br が悪い
            = f.submit "検索", class: "search-more-button"

      .main_contents__box__contents__search__right
        .main_contents__box__contents__title_box
          .main_contents__box__contents__title_box__title
            %h2
              = "'#{params[:search]}' の検索結果"
        .main_contents__box__contents__items_search
          - @items.zip(@images, @trade).each do |item, image, trade|
            .main_contents__box__contents__items__one
              - if trade.sale_state != "exhibit"
                .sold_item
                  %p SOLD
                = image_tag image.url.url, class: "index_image"
              -else
                = image_tag image.url.url, class: "index_image"
              .main_contents__box__contents__items__one__image__price
                = "¥#{item.price}"
              .main_contents__box__contents__items__one__title
                %span
                  = link_to "/items/#{item.id}", method: :get do
                    = item.item_name

= render "footer"